"""
image_providers/gemini_imagen.py — Google Gemini Imagen 3 provider.
"""

import base64
import os
import time
from pathlib import Path

import requests

from lib.image_providers.base import ImageProvider

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


class GeminiImagenProvider(ImageProvider):
    """Generate images using Google Gemini Imagen 3."""

    def __init__(self):
        self.api_key = os.environ.get("GEMINI_API_KEY", "")
        self.model = "imagen-3.0-generate-002"  # Latest Imagen model
        self.base_url = "https://generativelanguage.googleapis.com/v1beta"

    @property
    def name(self) -> str:
        return "gemini_imagen"

    def is_available(self) -> bool:
        return bool(self.api_key)

    def generate_image(self, prompt: str, width: int = 1080, height: int = 1080) -> str:
        """
        Generate image via Gemini Imagen API.
        Returns: Local file path to the saved image.
        """
        if not self.api_key:
            raise RuntimeError("GEMINI_API_KEY not set")

        # Gemini Imagen API endpoint
        url = f"{self.base_url}/models/{self.model}:predict"
        params = {"key": self.api_key}

        payload = {
            "instances": [{"prompt": prompt}],
            "parameters": {
                "sampleCount": 1,
                "aspectRatio": self._get_aspect_ratio(width, height),
            },
        }

        response = requests.post(url, params=params, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()

        # Extract base64 image from response
        predictions = data.get("predictions", [])
        if not predictions:
            raise RuntimeError("No image generated by Gemini Imagen")

        image_data = predictions[0].get("bytesBase64Encoded", "")
        if not image_data:
            raise RuntimeError("Empty image data from Gemini Imagen")

        # Save to file
        output_dir = PROJECT_ROOT / "images"
        output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = int(time.time())
        output_path = output_dir / f"ai_generated_{timestamp}.png"

        with open(output_path, "wb") as f:
            f.write(base64.b64decode(image_data))

        return str(output_path)

    def _get_aspect_ratio(self, width: int, height: int) -> str:
        ratio = width / height
        if ratio > 1.1:
            return "16:9"
        elif ratio < 0.9:
            return "9:16"
        return "1:1"
